import { DNO_ITEM_SETS, DNO_CLASSES, DNO_ITEM_PIECE_TYPE } from "./types/enums"

export const SWITCH_SETS: any = {
  [DNO_ITEM_SETS.MINOTAUR]: "Red Army",
  [DNO_ITEM_SETS.CERBERUS]: "Cerberus",
  [DNO_ITEM_SETS.MANTICORE]: "Manticore",
  [DNO_ITEM_SETS.APOCALYPSE]: "Apocalypse",
  [DNO_ITEM_SETS.ARCHBISHOP]: "Ancient Totem",
  [DNO_ITEM_SETS.GIGANTES]: "Immortal",
  [DNO_ITEM_SETS.DANGEROUS]: "Dangerous desire's",
  [DNO_ITEM_SETS.TWISTED]: "Twisted obsession",
  [DNO_ITEM_SETS.HONOURABLE]: "Honourable tribe's",
  [DNO_ITEM_SETS.FULL_MOON]: "Full Moon Maple",
  [DNO_ITEM_SETS.NEW_MOON]: "New Moon Maple",
  [DNO_ITEM_SETS.FLINT]: "Flint",
  [DNO_ITEM_SETS.CINDER]: "Cinder",
  [DNO_ITEM_SETS.EMERALD]: "Emerald Dragon",
  [DNO_ITEM_SETS.DESERT]: "Desert Dragon",
  [DNO_ITEM_SETS.BLACK]: "Black Dragon",
  [DNO_ITEM_SETS.SEA_LEGEND]: "Sea Dragon",
  [DNO_ITEM_SETS.EMERALD_LEGEND]: "Emerald Dragon",
  [DNO_ITEM_SETS.DESERT_LEGEND]: "Desert Dragon",
  [DNO_ITEM_SETS.BLACK_LEGEND]: "Black Dragon",
}

export const SWITCH_SETS_PIECE_BY_CLASS: any = {
  [DNO_CLASSES.ACADEMIC]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Cannon",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Bubble Gun",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Mecha Glove",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Beret",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Slacks",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Power Mitten",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Shoes",
  },
  [DNO_CLASSES.ARCHER]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Longbow",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Crossbow",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Shortbow",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Headband",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Leggings",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Mitten",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Booties",
  },
  [DNO_CLASSES.ASSASSIN]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Scimitar",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Dagger",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Arm Blade",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Mask",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Vest",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Greaves",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Sandals",
  },
  [DNO_CLASSES.CLERIC]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Mace",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Flail",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Wand",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG_2]: "Shield",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Galero",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Armour",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Trousers",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Cuffs",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Shoes",
  },
  [DNO_CLASSES.KALI]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Fan",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Chakram",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Charm",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Orni",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Chori",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Salwar",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Rakki",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Jutti",
  },
  [DNO_CLASSES.LANCEA]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Spear",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Bracelets",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Bonnet",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Blouse",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Knee Socks",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Gloves",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Sandals",
  },
  [DNO_CLASSES.SORCERESS]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Spellbook",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Orb",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG_2]: "Voodoo Doll",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Staff",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Tiara",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Robe",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Tights",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Muff",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Heels",
  },
  [DNO_CLASSES.WARRIOR]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Sword",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Axe",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG_2]: "Hammer",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Guanlets",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Helmet",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Shirt",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Pants",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Gloves",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Boots",
  }
}

export const SWITCH_LEGEND_SETS_PIECE_BY_CLASS: any = {
  [DNO_CLASSES.ACADEMIC]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Coordinator Cannon",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Changer Bubble Gun",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Coordinator Mecha Glove",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Changer Mecha Glove",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Coordinator Beret",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Changer Beret",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Coordinator Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Changer Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Coordinator Slacks",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Changer Slacks",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Coordinator Power Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Changer Power Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Coordinator Round Shoes",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Changer Round Shoes",
  },
  [DNO_CLASSES.ARCHER]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Troublemaker Shortbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Tracker Longbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_3]: "Tracker Crossbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Tracker Quiver",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Troublemaker Quiver",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Tracker Headband",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Troublemaker headband",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Tracker Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Troublemaker Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Tracker Leggings",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Troublemaker Leggings",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Tracker Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Troublemaker Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Tracker Booties",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Troublemaker Booties",
  },
  [DNO_CLASSES.ASSASSIN]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Slaughter Scimitar",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Meditation Dagger",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Slaughter Arm Blade",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Meditation Arm Blade",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Slaughter Mask",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Meditation Mask",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Slaughter Vest",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Meditation Vest",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Slaughter Greaves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Meditation Greaves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Slaughter Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Meditation Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Slaughter Sandals",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Meditation Sandals",
  },
  [DNO_CLASSES.CLERIC]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Guardian Knight Mace",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Guardian Knight Flail",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Saviour Wand",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Guardian Knight Shield",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_3]: "Saviour Shield",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Guardian Knight Galero",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Saviour Galero",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Guardian Knight Armour",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Saviour Armour",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Guardian Knight Trousers",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Saviour Trousers",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Guardian Knight Cuffs",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Saviour Cuffs",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Guardian Knight Shoes",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Saviour Shoes",
  },
  [DNO_CLASSES.KALI]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Soul handler Fan",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Dancer Chakram",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Dancer Charm",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Soul handler Charm",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Dancer Orni",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Soul handler Orni",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Dancer Chori",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Soul handler Chori",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Dancer Salwar",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Soul handler Salwar",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Dancer Rakki",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Soul handler Rakki",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Dancer Jutti",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Soul handler Jutti",
  },
  [DNO_CLASSES.LANCEA]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Victoria Spear",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Victoria Bracelets",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Victoria Bonnet",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Victoria Blouse",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Victoria Knee Socks",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Victoria Gloves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Victoria Sandals",
  },
  [DNO_CLASSES.SORCERESS]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Terminator Spellbook",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Contractor Spellbook",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Terminator Orb",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Contractor Orb",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_3]: "Terminator Voodoo Doll",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_3]: "Contractor Voodoo Doll",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_4]: "Terminator Staff",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_4]: "Contractor Staff",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Terminator Tiara",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Contractor Tiara",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Terminator Robe",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Contractor Robe",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Terminator Tights",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Contractor Tights",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Terminator Muffs",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Contractor Muffs",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Terminator Heels",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Contractor Heels",
  },
  [DNO_CLASSES.WARRIOR]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Destroyer Sword",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Illumia Axe",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Illumia Hammer",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Destroyer Gaunlets",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_3]: "Illumia Gaunlets",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Destroyer Helmet",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Illumia Helmet",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Destroyer Shirt",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Illumia Shirt",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Destroyer Pants",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Illumia Pants",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Destroyer Gloves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Illumia Gloves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Destroyer Boots",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Illumia Boots",
  }
}