import { DNO_ITEM_SETS, DNO_CLASSES, DNO_ITEM_PIECE_TYPE } from "./types/enums"

export const SWITCH_SETS: any = {
  [DNO_ITEM_SETS.MINOTAUR]: "Red Army",
  [DNO_ITEM_SETS.CERBERUS]: "Cerberus",
  [DNO_ITEM_SETS.MANTICORE]: "Manticore",
  [DNO_ITEM_SETS.APOCALYPSE]: "Apocalypse",
  [DNO_ITEM_SETS.ARCHBISHOP]: "Ancient Totem",
  [DNO_ITEM_SETS.GIGANTES]: "Inmortal",
  [DNO_ITEM_SETS.DANGEROUS]: "Dangerous desire's",
  [DNO_ITEM_SETS.TWISTED]: "Twisted obsession",
  [DNO_ITEM_SETS.HONOURABLE]: "Honourable tribe's",
  [DNO_ITEM_SETS.FULL_MOON]: "Full Moon Maple",
  [DNO_ITEM_SETS.NEW_MOON]: "New Moon Maple",
  [DNO_ITEM_SETS.FLINT]: "Flint",
  [DNO_ITEM_SETS.CINDER]: "Cinder",
  [DNO_ITEM_SETS.EMERALD]: "Emerald Dragon",
  [DNO_ITEM_SETS.DESERT]: "Desert Dragon",
  [DNO_ITEM_SETS.BLACK]: "Black Dragon",
  [DNO_ITEM_SETS.SEA_LEGEND]: "Sea Dragon",
  [DNO_ITEM_SETS.EMERALD_LEGEND]: "Emerald Dragon",
  [DNO_ITEM_SETS.DESERT_LEGEND]: "Desert Dragon",
  [DNO_ITEM_SETS.BLACK_LEGEND]: "Black Dragon",
}

export const SWITCH_SETS_PIECE_BY_CLASS: any = {
  [DNO_CLASSES.ACADEMIC]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Cannon",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Bubble Gun",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Mecha Gloves",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Beret",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Slacks",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Power Mitten",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Shoes",
  },
  [DNO_CLASSES.ARCHER]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Longbow",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Crossbow",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Shortbow",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Headband",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Leggings",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Mitten",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Booties",
  },
  [DNO_CLASSES.ASSASSIN]: {
    [DNO_ITEM_PIECE_TYPE.WEAPON]: "Scimitar",
    [DNO_ITEM_PIECE_TYPE.WEAPON_MAG]: "Dagger",
    [DNO_ITEM_PIECE_TYPE.SECONDARY]: "Arm Blade",
    [DNO_ITEM_PIECE_TYPE.HELM]: "Mask",
    [DNO_ITEM_PIECE_TYPE.ARMOUR]: "Vest",
    [DNO_ITEM_PIECE_TYPE.LEGS]: "Greaves",
    [DNO_ITEM_PIECE_TYPE.GLOVES]: "Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.SHOES]: "Sandals",
  }
}

export const SWITCH_LEGEND_SETS_PIECE_BY_CLASS: any = {
  [DNO_CLASSES.ACADEMIC]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Coordinator Cannon",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Changer Bubble Gun",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Coordinator Mecha Gloves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Changer Mecha Gloves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Coordinator Beret",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Changer Beret",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Coordinator Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Changer Tunic",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Coordinator Slacks",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Changer Slacks",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Coordinator Power Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Changer Power Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Coordinator Round Shoes",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Changer Round Shoes",
  },
  [DNO_CLASSES.ARCHER]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Troublemaker Shortbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Tracker Longbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_3]: "Tracker Crossbow",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Tracker Quiver",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Troublemaker Quiver",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Tracker Headband",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Troublemaker headband",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Tracker Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Troublemaker Onesie",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Tracker Leggings",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Troublemaker Leggings",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Tracker Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Troublemaker Mitten",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Tracker Booties",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Troublemaker Booties",
  },
  [DNO_CLASSES.ASSASSIN]: {
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_1]: "Slaughter Scimitar",
    [DNO_ITEM_PIECE_TYPE.LEGEND_WEAPON_2]: "Meditation Dagger",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_1]: "Slaughter Arm Blade",
    [DNO_ITEM_PIECE_TYPE.LEGEND_SECONDARY_2]: "Meditation Arm Blade",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_1]: "Slaughter Mask",
    [DNO_ITEM_PIECE_TYPE.LEGEND_HELM_2]: "Meditation Mask",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_1]: "Slaughter Vest",
    [DNO_ITEM_PIECE_TYPE.LEGEND_ARMOUR_2]: "Meditation Vest",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_1]: "Slaughter Greaves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_LEGS_2]: "Meditation Greaves",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_1]: "Slaughter Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.LEGEND_GLOVES_2]: "Meditation Wrist Guards",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_1]: "Slaughter Sandals",
    [DNO_ITEM_PIECE_TYPE.LEGEND_BOOTS_2]: "Meditation Sandals",
  }
}